#!/usr/bin/env python

import sys
import os

l = [ '/usr/lib/vmware/include/vmci', '/usr/lib/vmware-tools/include/vmci' ]
for i in l:
    if os.path.isdir(i):
        sys.stdout.write('-I%s\n' % (i,))
        sys.exit(0)
else:
    sys.stderr.write("vmci-cflags: can't find VMCI headers in %s" % (l,))
    sys.exit(1)
